name: Test project

on:
  push:
    branches:
      - test-CI
  pull_request:
    branches:
      - test-CI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        name: Cache Cargo registry + index
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ runner.os }}-v0000-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v2
        name: Get npm cache directory
        with:
          path: |
            ~/.npm/
          key: npm-${{ runner.os }}-v0000-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: install global mocha
        run: |
          npm install -g mocha
          npm install -g ts-mocha
          npm install -g typescript
          ts-mocha -h
      - name: install solana
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev
          sh -c "$(curl -sSfL https://release.solana.com/v1.7.11/install)"
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          solana-keygen new
      - name: install
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          npm install -g @project-serum/anchor
          cargo install --git https://github.com/project-serum/anchor anchor-cli --locked
          npm install
      - name: build programs
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          anchor build

      - name: build sdk
        run: |
          npm install
          npm run build
        working-directory: ./sdk
      # - name: test
      #   run: |
      #     export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
      #     npm run test:full
      #     cargo test
